[unstable]
build-std = ["core", "alloc", "std", "panic_abort"]
build-std-features = ["panic_immediate_abort"]
strip = true

[build]
target = "x86_64-pc-windows-gnu"

[target]
[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
rustflags = [
    "-Z", "location-detail=none",
    "-C", "link-arg=-s",
    "-C", "link-arg=-Wl,--gc-sections",
    "-C", "link-arg=-Wl,--strip-all",
    "-C", "target-feature=+crt-static",
    "-C", "prefer-dynamic=false",
    "-C", "embed-bitcode=false",
    "-C", "debuginfo=0",
    "-C", "symbol-mangling-version=v0",
    "-Z", "share-generics=off",
    "-Z", "threads=1",
    "-Z", "unstable-options"
]

[target.x86_64-unknown-linux-musl]
linker = "rust-lld"